export const pizzaData = [
  {
    id: 1,
    name: "Margherita",
    isVeg: true,
    description: "Classic tomato and mozzarella cheese pizza.",
    rating: 4.5,
    price: 10.99,
    size: ["Small", "Medium", "Large"],
    toppings: ["Tomato Sauce", "Mozzarella Cheese", "Basil"],
    img_url: `./../images/1.jpg`,
  },
  {
    id: 2,
    name: "Pepperoni",
    isVeg: false,
    description: "Spicy pepperoni and mozzarella cheese pizza.",
    rating: 4.0,
    price: 12.99,
    size: ["Small", "Medium", "Large"],
    toppings: ["Tomato Sauce", "Mozzarella Cheese", "Pepperoni"],
    img_url: `./../images/2.jpg`,
  },
  {
    id: 3,
    name: "Hawaiian",
    isVeg: false,
    description: "Ham, pineapple, and mozzarella cheese pizza.",
    rating: 3.8,
    price: 11.99,
    size: ["Small", "Medium", "Large"],
    toppings: ["Tomato Sauce", "Mozzarella Cheese", "Ham", "Pineapple"],
    img_url: `./../images/3.jpg`,
  },
  {
    id: 4,
    name: "Veggie Supreme",
    isVeg: true,
    description: "A medley of fresh vegetables and cheese.",
    rating: 4.2,
    price: 11.99,
    size: ["Small", "Medium", "Large"],
    toppings: [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Bell Peppers",
      "Mushrooms",
      "Olives",
    ],
    img_url: `./../images/4.jpg`,
  },
  {
    id: 5,
    name: "BBQ Chicken",
    isVeg: false,
    description: "Tangy BBQ sauce, chicken, and mozzarella cheese pizza.",
    rating: 4.3,
    price: 13.99,
    size: ["Small", "Medium", "Large"],
    toppings: ["BBQ Sauce", "Mozzarella Cheese", "Chicken", "Onions"],
    img_url: `./../images/5.jpg`,
  },
  {
    id: 6,
    name: "Mushroom Lovers",
    isVeg: true,
    description: "A mushroom delight with mozzarella cheese.",
    rating: 4.1,
    price: 12.99,
    size: ["Small", "Medium", "Large"],
    toppings: ["Tomato Sauce", "Mozzarella Cheese", "Mushrooms"],
    img_url: `./../images/6.jpg`,
  },
  {
    id: 7,
    name: "Supreme",
    isVeg: false,
    description: "A pizza loaded with all the toppings.",
    rating: 4.4,
    price: 14.99,
    size: ["Small", "Medium", "Large"],
    toppings: [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Pepperoni",
      "Bell Peppers",
      "Mushrooms",
      "Olives",
      "Onions",
    ],
    img_url: `./../images/7.jpg`,
  },
  {
    id: 8,
    name: "Cheese Lover's",
    isVeg: true,
    description: "A cheesy delight with extra mozzarella cheese.",
    rating: 4.6,
    price: 11.99,
    size: ["Small", "Medium", "Large"],
    toppings: ["Tomato Sauce", "Extra Mozzarella Cheese"],
    img_url: `./../images/8.jpg`,
  },
  {
    id: 9,
    name: "Meat Feast",
    isVeg: false,
    description: "A meat lover's dream with various meats and cheese.",
    rating: 4.5,
    price: 15.99,
    size: ["Small", "Medium", "Large"],
    toppings: [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Pepperoni",
      "Sausage",
      "Ham",
      "Bacon",
    ],
    img_url: `./../images/9.jpg`,
  },
  {
    id: 10,
    name: "Veggie Delight",
    isVeg: true,
    description:
      "A vegetarian delight with fresh veggies and mozzarella cheese.",
    rating: 3.0,
    price: 12.99,
    size: ["Small", "Medium", "Large"],
    toppings: [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Bell Peppers",
      "Mushrooms",
      "Olives",
      "Onions",
    ],
    img_url: `./../images/10.jpg`,
  },
  {
    id: 11,
    name: "Chicken Alfredo",
    isVeg: false,
    description: "Creamy Alfredo sauce, chicken, and mozzarella cheese pizza.",
    rating: 4.4,
    price: 13.99,
    size: ["Small", "Medium", "Large"],
    toppings: ["Alfredo Sauce", "Mozzarella Cheese", "Chicken", "Broccoli"],
    img_url: `./../images/11.jpg`,
  },
  {
    id: 12,
    name: "Spicy Veggie",
    isVeg: true,
    description: "A spicy twist with fresh veggies and mozzarella cheese.",
    rating: 3.2,
    price: 11.99,
    size: ["Small", "Medium", "Large"],
    toppings: [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Bell Peppers",
      "Jalapenos",
    ],
    img_url: `./../images/12.jpg`,
  },
  {
    id: 13,
    name: "Four Cheese",
    isVeg: true,
    description: "A blend of four delicious cheeses.",
    rating: 4.6,
    price: 12.99,
    size: ["Small", "Medium", "Large"],
    toppings: [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Parmesan Cheese",
      "Cheddar Cheese",
      "Feta Cheese",
    ],
    img_url: `./../images/13.jpg`,
  },
  {
    id: 14,
    name: "Sausage Supreme",
    isVeg: false,
    description: "A sausage lover's paradise with mozzarella cheese.",
    rating: 4.3,
    price: 12.99,
    size: ["Small", "Medium", "Large"],
    toppings: [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Sausage",
      "Bell Peppers",
      "Onions",
    ],
    img_url: `./../images/14.jpg`,
  },
  {
    id: 15,
    name: "Buffalo Chicken",
    isVeg: false,
    description: "Spicy buffalo sauce, chicken, and mozzarella cheese pizza.",
    rating: 4.1,
    price: 13.99,
    size: ["Small", "Medium", "Large"],
    toppings: [
      "Buffalo Sauce",
      "Mozzarella Cheese",
      "Chicken",
      "Ranch Dressing",
    ],
    img_url: `./../images/15.jpg`,
  },
  {
    id: 16,
    name: "Pesto Veggie",
    isVeg: true,
    description:
      "Fresh pesto sauce with a medley of veggies and mozzarella cheese.",
    rating: 4.2,
    price: 11.99,
    size: ["Small", "Medium", "Large"],
    toppings: [
      "Pesto Sauce",
      "Mozzarella Cheese",
      "Tomatoes",
      "Bell Peppers",
      "Olives",
    ],
    img_url: `./../images/16.jpg`,
  },
  {
    id: 17,
    name: "Bacon Deluxe",
    isVeg: false,
    description: "Loaded with bacon, cheese, and more.",
    rating: 4.5,
    price: 14.99,
    size: ["Small", "Medium", "Large"],
    toppings: [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Bacon",
      "Onions",
      "Jalapenos",
    ],
    img_url: `./../images/17.jpg`,
  },
  {
    id: 18,
    name: "Spinach and Feta",
    isVeg: true,
    description: "Fresh spinach and feta cheese pizza.",
    rating: 3.4,
    price: 12.99,
    size: ["Small", "Medium", "Large"],
    toppings: [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Spinach",
      "Feta Cheese",
      "Olives",
    ],
    img_url: `./../images/18.jpg`,
  },
  {
    id: 19,
    name: "BBQ Veggie",
    isVeg: true,
    description: "BBQ sauce with fresh veggies and mozzarella cheese.",
    rating: 4.0,
    price: 11.99,
    size: ["Small", "Medium", "Large"],
    toppings: [
      "BBQ Sauce",
      "Mozzarella Cheese",
      "Bell Peppers",
      "Mushrooms",
      "Onions",
    ],
    img_url: `./../images/19.jpg`,
  },
  {
    id: 20,
    name: "Chicken Tikka",
    isVeg: false,
    description: "Tandoori chicken and mozzarella cheese pizza.",
    rating: 3.8,
    price: 13.99,
    size: ["Small", "Medium", "Large"],
    toppings: [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Chicken Tikka",
      "Onions",
      "Bell Peppers",
    ],
    img_url: `./../images/20.jpg`,
  },
];
